// Command gendocs renders docs/tools/<name>.md from the live tool registry —
// the same schemas the server advertises over MCP — so the reference pages
// cannot drift from the code. `gendocs -check` (the docs CI job) exits
// non-zero when a page on disk differs from what it would generate.
package main

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"

	"github.com/aws/aws-sdk-go-v2/service/pinpointsmsvoicev2"
	"github.com/aws/aws-sdk-go-v2/service/s3"
	"github.com/aws/aws-sdk-go-v2/service/sesv2"
	"github.com/modelcontextprotocol/go-sdk/mcp"

	"github.com/gesparza8138/aws-messaging-mcp/internal/mcpserver"
	"github.com/gesparza8138/aws-messaging-mcp/internal/settings"
)

// stubSES and stubEUM satisfy the client interfaces so every tool family
// registers; gendocs only lists tools and never calls them.
type stubSES struct{}

func (stubSES) SendEmail(context.Context, *sesv2.SendEmailInput, ...func(*sesv2.Options)) (*sesv2.SendEmailOutput, error) {
	return nil, nil
}

func (stubSES) ListEmailIdentities(context.Context, *sesv2.ListEmailIdentitiesInput, ...func(*sesv2.Options)) (*sesv2.ListEmailIdentitiesOutput, error) {
	return nil, nil
}

func (stubSES) GetAccount(context.Context, *sesv2.GetAccountInput, ...func(*sesv2.Options)) (*sesv2.GetAccountOutput, error) {
	return nil, nil
}

type stubEUM struct{}

func (stubEUM) SendTextMessage(context.Context, *pinpointsmsvoicev2.SendTextMessageInput, ...func(*pinpointsmsvoicev2.Options)) (*pinpointsmsvoicev2.SendTextMessageOutput, error) {
	return nil, nil
}

func (stubEUM) SendMediaMessage(context.Context, *pinpointsmsvoicev2.SendMediaMessageInput, ...func(*pinpointsmsvoicev2.Options)) (*pinpointsmsvoicev2.SendMediaMessageOutput, error) {
	return nil, nil
}

func (stubEUM) DescribePhoneNumbers(context.Context, *pinpointsmsvoicev2.DescribePhoneNumbersInput, ...func(*pinpointsmsvoicev2.Options)) (*pinpointsmsvoicev2.DescribePhoneNumbersOutput, error) {
	return nil, nil
}

type stubFiles struct{}

func (stubFiles) PutObject(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	return nil, nil
}

func (stubFiles) HeadObject(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) (*s3.HeadObjectOutput, error) {
	return nil, nil
}

func (stubFiles) CopyObject(context.Context, *s3.CopyObjectInput, ...func(*s3.Options)) (*s3.CopyObjectOutput, error) {
	return nil, nil
}

func (stubFiles) DeleteObject(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) (*s3.DeleteObjectOutput, error) {
	return nil, nil
}

func (stubFiles) ListObjectsV2(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
	return nil, nil
}

func main() {
	check := flag.Bool("check", false, "verify pages match instead of writing")
	dir := flag.String("dir", "docs/tools", "output directory")
	flag.Parse()
	if err := run(*check, *dir); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run(check bool, dir string) error {
	ctx := context.Background()
	server := mcpserver.NewServer(mcpserver.Deps{Settings: settings.Settings{}, SES: stubSES{}, EUM: stubEUM{}, Files: stubFiles{}})
	clientTransport, serverTransport := mcp.NewInMemoryTransports()
	serverSession, err := server.Connect(ctx, serverTransport, nil)
	if err != nil {
		return err
	}
	defer func() { _ = serverSession.Close() }()
	client := mcp.NewClient(&mcp.Implementation{Name: "gendocs", Version: "0"}, nil)
	session, err := client.Connect(ctx, clientTransport, nil)
	if err != nil {
		return err
	}
	defer func() { _ = session.Close() }()

	tools, err := session.ListTools(ctx, nil)
	if err != nil {
		return err
	}
	pages := map[string][]byte{filepath.Join(dir, "README.md"): index(tools.Tools)}
	for _, tool := range tools.Tools {
		page, err := render(tool)
		if err != nil {
			return fmt.Errorf("%s: %w", tool.Name, err)
		}
		pages[filepath.Join(dir, tool.Name+".md")] = page
	}

	var stale []string
	for path, want := range pages {
		if check {
			got, err := os.ReadFile(path) // #nosec G304 -- paths are built from tool names, not user input
			if err != nil || !bytes.Equal(got, want) {
				stale = append(stale, path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(path), 0o750); err != nil {
			return err
		}
		if err := os.WriteFile(path, want, 0o600); err != nil {
			return err
		}
	}
	if len(stale) > 0 {
		sort.Strings(stale)
		return fmt.Errorf("stale tool docs (run `go run ./cmd/gendocs`): %v", stale)
	}
	return nil
}

func index(tools []*mcp.Tool) []byte {
	var b bytes.Buffer
	b.WriteString("<!-- generated by cmd/gendocs; do not edit -->\n\n# Tool reference\n\n")
	b.WriteString("| Tool | Description |\n| --- | --- |\n")
	for _, tool := range tools {
		fmt.Fprintf(&b, "| [`%s`](%s.md) | %s |\n", tool.Name, tool.Name, tool.Description)
	}
	return b.Bytes()
}

func render(tool *mcp.Tool) ([]byte, error) {
	var b bytes.Buffer
	fmt.Fprintf(&b, "<!-- generated by cmd/gendocs; do not edit -->\n\n# `%s`\n\n%s\n", tool.Name, tool.Description)
	if err := schemaBlock(&b, "Input schema", tool.InputSchema); err != nil {
		return nil, err
	}
	if err := schemaBlock(&b, "Output schema", tool.OutputSchema); err != nil {
		return nil, err
	}
	return b.Bytes(), nil
}

func schemaBlock(b *bytes.Buffer, title string, schema any) error {
	if schema == nil {
		return nil
	}
	raw, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		return err
	}
	fmt.Fprintf(b, "\n## %s\n\n```json\n%s\n```\n", title, raw)
	return nil
}
